openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/jm-root/jm-mq-kafka/1.0.0
info:
  version: "1.0.0"
  title: jm-mq-kafka-api
  description: MQ系统API
paths:
  /mq/publish:
    post:
      description: 发布消息
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Message'
      responses:
        '200':
          description: 结果
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ret'
  /mq/produce:
    post:
      description: 生产消息
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Message'
      responses:
        '200':
          description: 结果
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ret'

components:
  schemas:
    Ret:
      type: object
      properties:
        ret:
          type: integer
          format: int32
          description: 1 成功 0 失败
      description: 操作结果
    Message:
      type: object
      properties:
        topic:
          type: string
          example: 'user.save'
        message:
          type: string | object
      description: 消息
